name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            unit_test_exec: .\UnitTest.cmd
          - os: macos-latest
            unit_test_exec: ./UnitTest.sh
          - os: ubuntu-latest
            unit_test_exec: ./UnitTest.sh

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: configure
      run: |
            mkdir build
            cd build
            cmake ..
    - name: build
      run: |
            cd build
            cmake --build .
    - name: Test
      run: |
            cd build
            ${{ matrix.unit_test_exec }}

