name: CodeCov - CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}

    strategy:
       matrix:
         os: [macos-latest, windows-latest]
         include:
           - os: windows-latest
             unit_test_exec: |
                            cd Debug
                            .\UnitTest.exe
           - os: macos-latest
             unit_test_exec: ./UnitTest

    steps:
    - uses: actions/checkout@master
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: configure
      run: |
            mkdir build
            cd build
            cmake ..
    - name: build
      run: |
            cd build
            cmake --build .
    - name: Test
      run: |
            cd bin
            ${{ matrix.unit_test_exec }}

  cover:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: configure
      run: |
            mkdir build
            cd build
            cmake -DUSE_COV=TRUE ..
    - name: build
      run: |
            cd build
            make -j
    - name: Test
      run: |
            cd bin
            ./UnitTest
    - uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        verbose: true # optional (default = false)
